const constants = {
  calibartionTerms: ["calibration", "calibrate", "calibrated", "calibrating"],
  positiveCategories: ["deposits", "trendUp", "salary"],
  neutralCategories: ["investments"],
  negativeCategories: [
    "food",
    "shopping",
    "transport",
    "health",
    "entertainment",
    "education",
    "home",
    "bills",
    "gifts",
    "other",
    "trendDown",
  ],
  allowed: {
    sources: ["barclays", "revolut", "cash"],
    currencies: ["USD", "EUR", "GBP"],
    categories: [
      "food",
      "shopping",
      "transport",
      "health",
      "entertainment",
      "education",
      "home",
      "bills",
      "gifts",
      "other",
      "deposits",
      "salary",
      "investments",
      "trendUp",
      "trendDown",
    ],
    importStates: ["running", "success", "error"],
    transactionStatusFilters: ["active", "inactive"],
    amountFilters: [
      "incomeOnly",
      "moreThan10Spent",
      "moreThan25Spent",
      "moreThan50Spent",
      "moreThan100Spent",
      "moreThan250Spent",
    ],
    investmentEventTypes: ["deposit", "adjustment", "withdrawal", "created"],
  },
  sessionMaxAge: 259200, // number in seconds (3days)
};

export default constants;
