import { Transaction } from "@utils/Types";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    date: new Date("2021-01-01"),
    category: "food",
    amount: -10,
    currency: "USD",
    description: "McDonalds",
    source: "cash",
  },
  {
    id: "2",
    date: new Date("2021-01-02"),
    category: "shopping",
    amount: -20,
    currency: "USD",
    description: "Amazon",
    source: "revolut",
  },
  {
    id: "3",
    date: new Date("2021-01-03"),
    category: "transport",
    amount: -30.21,
    currency: "USD",
    description: "Uber",
    source: "cash",
  },
  {
    id: "4",
    date: new Date("2021-01-04"),
    category: "health",
    amount: -40,
    currency: "USD",
    description: "Doctor",
    source: "cash",
  },
  {
    id: "5",
    date: new Date("2021-01-05"),
    category: "entertainment",
    amount: -50,
    currency: "USD",
    description: "Movie",
    source: "cash",
  },
  {
    id: "6",
    date: new Date("2021-01-06"),
    category: "education",
    amount: -60,
    currency: "USD",
    description: "Books",
    source: "cash",
  },
  {
    id: "7",
    date: new Date("2021-01-07"),
    category: "home",
    amount: -70,
    currency: "USD",
    description: "Furniture",
    source: "cash",
  },
  {
    id: "8",
    date: new Date("2021-01-08"),
    category: "bills",
    amount: -80,
    currency: "USD",
    description: "Electricity",
    source: "cash",
  },
  {
    id: "9",
    date: new Date("2021-01-09"),
    category: "gifts",
    amount: -90,
    currency: "USD",
    description: "Gift",
    source: "cash",
  },
  {
    id: "10",
    date: new Date("2021-01-10"),
    category: "other",
    amount: -100,
    currency: "USD",
    description: "Other",
    source: "cash",
  },
  {
    id: "11",
    date: new Date("2021-01-11"),
    category: "deposits",
    amount: 110,
    currency: "USD",
    description: "Deposit",
    source: "cash",
  },
  {
    id: "12",
    date: new Date("2021-01-12"),
    category: "salary",
    amount: 120.12,
    currency: "USD",
    description: "Salary",
    source: "cash",
  },
  {
    id: "13",
    date: new Date("2021-01-13"),
    category: "transport",
    amount: -30.21,
    currency: "USD",
    description: "Uber",
    source: "cash",
  },
  {
    id: "14",
    date: new Date("2021-01-14"),
    category: "health",
    amount: -40,
    currency: "USD",
    description: "Doctor",
    source: "cash",
  },
  {
    id: "15",
    date: new Date("2021-01-15"),
    category: "entertainment",
    amount: -50,
    currency: "USD",
    description: "Movie",
    source: "cash",
  },
  {
    id: "16",
    date: new Date("2021-01-16"),
    category: "education",
    amount: -60,
    currency: "USD",
    description: "Books",
    source: "cash",
  },
  {
    id: "17",
    date: new Date("2021-01-17"),
    category: "home",
    amount: -70,
    currency: "USD",
    description: "Furniture",
    source: "cash",
  },
  {
    id: "18",
    date: new Date("2021-01-18"),
    category: "bills",
    amount: -80,
    currency: "USD",
    description: "Electricity",
    source: "cash",
  },
];
