import { Transaction } from "@utils/Types";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    date: "2021-01-01",
    category: "food",
    amount: -10,
    currency: "USD",
    description: "McDonalds",
  },
  {
    id: "2",
    date: "2021-01-02",
    category: "shopping",
    amount: -20,
    currency: "USD",
    description: "Amazon",
  },
  {
    id: "3",
    date: "2021-01-03",
    category: "transport",
    amount: -30.21,
    currency: "USD",
    description: "Uber",
  },
  {
    id: "4",
    date: "2021-01-04",
    category: "health",
    amount: -40,
    currency: "USD",
    description: "Doctor",
  },
  {
    id: "5",
    date: "2021-01-05",
    category: "entertainment",
    amount: -50,
    currency: "USD",
    description: "Movie",
  },
  {
    id: "6",
    date: "2021-01-06",
    category: "education",
    amount: -60,
    currency: "USD",
    description: "Books",
  },
  {
    id: "7",
    date: "2021-01-07",
    category: "home",
    amount: -70,
    currency: "USD",
    description: "Furniture",
  },
  {
    id: "8",
    date: "2021-01-08",
    category: "bills",
    amount: -80,
    currency: "USD",
    description: "Electricity",
  },
  {
    id: "9",
    date: "2021-01-09",
    category: "gifts",
    amount: -90,
    currency: "USD",
    description: "Gift",
  },
  {
    id: "10",
    date: "2021-01-10",
    category: "other",
    amount: -100,
    currency: "USD",
    description: "Other",
  },
  {
    id: "11",
    date: "2021-01-11",
    category: "deposits",
    amount: 110,
    currency: "USD",
    description: "Deposit",
  },
  {
    id: "12",
    date: "2021-01-12",
    category: "salary",
    amount: 120.12,
    currency: "USD",
    description: "Salary",
  },
  {
    id: "13",
    date: "2021-01-03",
    category: "transport",
    amount: -30.21,
    currency: "USD",
    description: "Uber",
  },
  {
    id: "14",
    date: "2021-01-04",
    category: "health",
    amount: -40,
    currency: "USD",
    description: "Doctor",
  },
  {
    id: "15",
    date: "2021-01-05",
    category: "entertainment",
    amount: -50,
    currency: "USD",
    description: "Movie",
  },
  {
    id: "16",
    date: "2021-01-06",
    category: "education",
    amount: -60,
    currency: "USD",
    description: "Books",
  },
  {
    id: "17",
    date: "2021-01-07",
    category: "home",
    amount: -70,
    currency: "USD",
    description: "Furniture",
  },
  {
    id: "18",
    date: "2021-01-08",
    category: "bills",
    amount: -80,
    currency: "USD",
    description: "Electricity",
  },
];
